---
releases:
  - name: homerun-redis-stack
    installed: true
    namespace: homerun
    chart: stuttgart-things/homerun
    version: v0.6.0
    values: |
      redis-stack:
        enabled: true
        sentinel:
          service:
            type: ClusterIP
        enabled: true
        global:
          redis:
            password: <path:cloud/data/test#redis_password>
        master:
          service:
            type: ClusterIP
          persistence:
            enabled: true
            storageClass: local-path
            size: 4Gi
        replica:
          persistence:
            enabled: false
            storageClass: local-path
            size: 4Gi

  - name: homerun-generic-pitcher
    installed: true
    namespace: homerun
    chart: stuttgart-things/homerun
    version: v0.6.0
    values: |
      generic-pitcher:
        enabled: true
        configmaps:
          homerun-generic-pitcher:
            API_PATH: generic
            PORT: "4000"
            REDIS_STREAM: homerun
            REDISEARCH_INDEX: homerun
        secrets:
          generic-token:
            name: generic-token
            labels:
              app: homerun-generic-pitcher
            dataType: stringData
            secretKVs:
              WEBHOOK_TOKEN: <path:cloud/data/test#homerun_generic_token>
          redis-connection-homerun-generic-pitcher:
            name: redis-connection-homerun-generic-pitcher
            labels:
              app: homerun-generic-pitcher
            dataType: stringData
            secretKVs:
              REDIS_SERVER: homerun-redis-stack-newyork-headless.homerun.svc.cluster.local
              REDIS_PORT: 6379
              REDIS_PASSWORD: <path:cloud/data/test#redis_password>
        customresources:
          homerun-generic-pitcher-certificate:
            apiVersion: cert-manager.io/v1
            kind: Certificate
            metadata:
              name: homerun-generic-pitcher-ingress
              labels:
                app: homerun-generic-pitcher
            spec:
              commonName: andre-rahul-blog-test-kind-2.labul.sva.de
              dnsNames:
                - andre-rahul-blog-test-kind-2.labul.sva.de
              issuerRef:
                name: ca-issuer
                kind: ClusterIssuer
              secretName: homerun-generic-pitcher-ingress-tls
        ingress:
          homerun-generic-pitcher-ingress:
            labels:
              app: homerun-generic-pitcher
            name: homerun-generic-pitcher
            ingressClassName: nginx
            annotations:
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
            service:
              name: homerun-generic-pitcher-service
              port: 80
              path: /generic
              pathType: Prefix
            hostname: andre-rahul-blog-test-kind-2
            domain: labul.sva.de
            tls:
              secretName: homerun-generic-pitcher-ingress-tls
              host: andre-rahul-blog-test-kind-2.labul.sva.de

  - name: homerun-text-catcher
    installed: true
    namespace: homerun
    chart: stuttgart-things/homerun
    version: v0.6.0
    values: |
      text-catcher:
        enabled: true
        configmaps:
          homerun-text-catcher:
            REDIS_STREAM: homerun
            LOGGING: terminal
        secrets:
          redis-connection-homerun-text-catcher:
            name: redis-connection-homerun-text-catcher
            labels:
              app: homerun-text-catcher
            dataType: stringData
            secretKVs:
              REDIS_SERVER: homerun-redis-stack-newyork-headless.homerun.svc.cluster.local
              REDIS_PORT: 6379
              REDIS_PASSWORD: <path:cloud/data/test#redis_password>

repositories:
  - name: stuttgart-things
    url: ghcr.io/stuttgart-things
    oci: true

helmDefaults:
  verify: false
  wait: true
  timeout: 600
  recreatePods: false
  force: true